name = "PortableStructs"
uuid = "b33d0e21-58ed-44e8-a1cd-54bcd6317649"
version = "0.1.0"
authors = ["Tucker McClure <tucker@gradient.team>"]

[workspace]
projects = ["test"]

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
OrderedCollections = "1.8.1"
Random = "1.11.0"
StaticArrays = "1.9.15"
YAML = "0.4.16"
